- Streetcode/Streetcode.BLL/DTO/AdditionalContent/Subtitles/SubtitleDTO.cs
- Streetcode/Streetcode.BLL/DTO/Feedback/ResponseDTO.cs
- Streetcode/Streetcode.BLL/DTO/Media/AudioDTO.cs
- Streetcode/Streetcode.BLL/DTO/Media/Images/ArtDTO.cs
- Streetcode/Streetcode.BLL/DTO/Media/Images/ImageDTO.cs
- Streetcode/Streetcode.BLL/DTO/Partners/PartnerDTO.cs
- Streetcode/Streetcode.BLL/DTO/Partners/PartnerSourceLinkDTO.cs
- Streetcode/Streetcode.BLL/DTO/Partners/StreetcodePartnerDTO.cs
- Streetcode/Streetcode.BLL/DTO/Sources/SourceLinkCategoryDTO.cs
- Streetcode/Streetcode.BLL/DTO/Sources/SourceLinkDTO.cs
- Streetcode/Streetcode.BLL/DTO/Streetcode/StreetcodeDTO.cs
- Streetcode/Streetcode.BLL/DTO/Streetcode/TextContent/FactDTO.cs
- Streetcode/Streetcode.BLL/DTO/Streetcode/Types/PersonStreetcodeDTO.cs
- Streetcode/Streetcode.BLL/DTO/Timeline/TimelineItemDTO.cs
- Streetcode/Streetcode.BLL/DTO/Toponyms/ToponymDTO.cs
- Streetcode/Streetcode.BLL/DTO/Transactions/TransactLinkDTO.cs
- Streetcode/Streetcode.DAL/Entities/Partners/Partner.cs
- Streetcode/Streetcode.DAL/Entities/Sources/SourceLink.cs
> Fixed all DTO-nullability

- Streetcode/Streetcode.DAL/Persistence/Migrations/20221227180254_AddCyrillicCollation.Designer.cs
- Streetcode/Streetcode.DAL/Persistence/Migrations/20221227180254_AddCyrillicCollation.cs
- Streetcode/Streetcode.DAL/Persistence/StreetcodeDbContext.cs
> add ukr collation to db

- Streetcode/Streetcode.BLL/DTO/Streetcode/StreetcodeDTO.cs
- Streetcode/Streetcode.BLL/Mapping/Media/Images/ArtProfile.cs
- Streetcode/Streetcode.BLL/Mapping/Toponyms/ToponymProfile.cs
- Streetcode/Streetcode.BLL/MediatR/Streetcode/Streetcode/GetById/GetStreetcodeByIdHandler.cs
improved streetcodeDTO with corresponding profiles and handlers
dev
ToDo
ToDo
ToDo
> improved streetcodeDTO

- Streetcode/Streetcode.BLL/MediatR/Media/Video/GetByStreetcodeId/GetVideoByStreetcodeIdQuery.cs
- Streetcode/Streetcode.BLL/MediatR/Media/Video/GetByStreetcodeId/GetVideoByStreetcodeIdQueryHandler.cs
- Streetcode/Streetcode.WebApi/Program.cs
> fixed GetVideoByStreetcodeIdQueryHandler

- Streetcode/Streetcode.BLL/Mapping/AdditionalContent/SubtitleProfile.cs
- Streetcode/Streetcode.BLL/MediatR/AdditionalContent/Subtitle/GetByStreetcodeId/GetSubtitlesByStreetcodeIdQuery.cs
- Streetcode/Streetcode.BLL/MediatR/AdditionalContent/Subtitle/GetByStreetcodeId/GetSubtitlesByStreetcodeIdQueryHandler.cs
- Streetcode/Streetcode.WebApi/Controllers/AdditionalContent/SubtitleController.cs
- Streetcode/Streetcode.WebApi/Program.cs
> Ticker api sync

- Streetcode/Streetcode.BLL/MediatR/Media/Audio/GetByStreetcodeId/GetAudioByStreetcodeIdQuery.cs
- Streetcode/Streetcode.BLL/MediatR/Media/Audio/GetByStreetcodeId/GetAudioByStreetcodeIdQueryHandler.cs
> fixed api audio

- Streetcode/Streetcode.BLL/DTO/Timeline/TimelineItemDTO.cs
- Streetcode/Streetcode.BLL/MediatR/Timeline/TimelineItem/GetAll/GetAllTimelineItemsHandler.cs
- Streetcode/Streetcode.BLL/MediatR/Timeline/TimelineItem/GetById/GetTimelineItemByIdHandler.cs
- Streetcode/Streetcode.BLL/MediatR/Timeline/TimelineItem/GetByStreetcodeId/GetTimelineItemByStreetcodeIdHandler.cs
> fix timeline mediatr and dto

- Streetcode/Streetcode.BLL/MediatR/Streetcode/Streetcode/WithIndexExist/StreetcodeWithIndexExistHandler.cs
- Streetcode/Streetcode.BLL/MediatR/Streetcode/Streetcode/WithIndexExist/StreetcodeWithIndexExistQuery.cs
- Streetcode/Streetcode.WebApi/Controllers/Streetcode/StreetcodeController.cs
> add new endpoint for checking if streetcode with index exist

- README.md
- Streetcode/Streetcode.BLL/DTO/AdditionalContent/CreateTagDTO.cs
- Streetcode/Streetcode.BLL/MediatR/AdditionalContent/Tag/Create/CreateTagHandler.cs
- Streetcode/Streetcode.BLL/MediatR/AdditionalContent/Tag/Create/CreateTagQuery.cs
- Streetcode/Streetcode.BLL/MediatR/Streetcode/RelatedFigure/GetByTagId/GetRelatedFiguresByTagIdHandler.cs
- Streetcode/Streetcode.BLL/MediatR/Streetcode/RelatedFigure/GetByTagId/GetRelatedFiguresByTagIdQuery.cs
- Streetcode/Streetcode.BLL/StreetCode.BLL.csproj
- Streetcode/Streetcode.DAL/Entities/Streetcode/StreetcodeContent.cs
- Streetcode/Streetcode.DAL/Repositories/Interfaces/Base/IRepositoryBase.cs
- Streetcode/Streetcode.DAL/Repositories/Realizations/Base/RepositoryBase.cs
- Streetcode/Streetcode.WebApi/Controllers/AdditionalContent/TagController.cs
- Streetcode/Streetcode.WebApi/Controllers/Streetcode/RelatedFigureController.cs
> Streetcode tag

- Streetcode/Streetcode.BLL/DTO/Streetcode/StreetcodeDTO.cs
- Streetcode/Streetcode.BLL/MediatR/Streetcode/Streetcode/GetByTransliterationUrl/GetStreetcodeByTransliterationUrlHandler.cs
- Streetcode/Streetcode.BLL/MediatR/Streetcode/Streetcode/GetByTransliterationUrl/GetStreetcodeByTransliterationUrlQuery.cs
- Streetcode/Streetcode.DAL/Entities/Streetcode/StreetcodeContent.cs
- Streetcode/Streetcode.DAL/Entities/Streetcode/TextContent/RelatedTerm.cs
- Streetcode/Streetcode.DAL/Extensions/ModelBuilderExtensions.cs
- Streetcode/Streetcode.DAL/Persistence/Migrations/20230323123612_AddTransliterationUrlToStreetcode.Designer.cs
- Streetcode/Streetcode.DAL/Persistence/Migrations/20230323123612_AddTransliterationUrlToStreetcode.cs
- Streetcode/Streetcode.WebApi/Controllers/Streetcode/StreetcodeController.cs
dev
PO request: Adding Transliteration for streetcodes
added Transliteration for streetcodes
Needs unit testing
> Transliteration urls for streetcodes

- Streetcode/Streetcode.BLL/DTO/Streetcode/RelatedFigureDTO.cs
- Streetcode/Streetcode.BLL/MediatR/Streetcode/RelatedFigure/Delete/DeleteRelatedFigureCommand.cs
- Streetcode/Streetcode.BLL/MediatR/Streetcode/RelatedFigure/Delete/DeleteRelatedFigureHandler.cs
- Streetcode/Streetcode.BLL/MediatR/Streetcode/RelatedFigure/Сreate/CreateRelatedFigureCommand.cs
- Streetcode/Streetcode.BLL/MediatR/Streetcode/RelatedFigure/Сreate/CreateRelatedFigureHandler.cs
- Streetcode/Streetcode.WebApi/Controllers/Streetcode/RelatedFigureController.cs
> post and delete methods

- Streetcode/Streetcode.BLL/DTO/Streetcode/StreetcodeDTO.cs
- Streetcode/Streetcode.BLL/MediatR/AdditionalContent/Tag/Create/CreateTagHandler.cs
- Streetcode/Streetcode.BLL/MediatR/Streetcode/Streetcode/GetByTransliterationUrl/GetStreetcodeByTransliterationUrlHandler.cs
- Streetcode/Streetcode.DAL/Repositories/Interfaces/Base/IRepositoryBase.cs
- Streetcode/Streetcode.DAL/Repositories/Realizations/Base/RepositoryBase.cs
- Streetcode/Streetcode.XUnitTest/MediatRTests/AdditionalContent/AdditionalContentTests/TagTests/CreateTagHandlerTests.cs
- Streetcode/Streetcode.XUnitTest/MediatRTests/StreetCode/Streetcode/GetStreetcodeByTransliterationUrlHandlerTests.cs
- Streetcode/Streetcode.XUnitTest/MediatRTests/Transactions/TransactionsTests/TransactionLinkTests/GetAllTransactLinksHandlerTests.cs
- Streetcode/Streetcode.XUnitTest/MediatRTests/Transactions/TransactionsTests/TransactionLinkTests/GetTransactLinkByIdHandlerTests.cs
- Streetcode/Streetcode.XUnitTest/MediatRTests/Transactions/TransactionsTests/TransactionLinkTests/GetTransactLinkByStreetcodeIdHandlerTests.cs
> unit tests for Transactions and GetByTransliterationUrl

- Streetcode/Streetcode.BLL/MediatR/Sources/SourceLink/Create/CreateCategoryCommand.cs
- Streetcode/Streetcode.BLL/MediatR/Sources/SourceLink/Create/CreateCategoryHandler.cs
- Streetcode/Streetcode.BLL/MediatR/Sources/SourceLink/Delete/DeleteCategoryCommand.cs
- Streetcode/Streetcode.BLL/MediatR/Sources/SourceLink/Delete/DeleteCategoryHandler.cs
- Streetcode/Streetcode.BLL/MediatR/Sources/SourceLink/Update/UpdateCategoryCommand.cs
- Streetcode/Streetcode.BLL/MediatR/Sources/SourceLink/Update/UpdateCategoryHandler.cs
- Streetcode/Streetcode.WebApi/Controllers/Source/SourcesController.cs
> SourcesCrud

- Streetcode/Streetcode.BLL/DTO/Streetcode/RelatedFigureDTO.cs
- Streetcode/Streetcode.BLL/Mapping/Streetcode/RelatedFigureProfile.cs
dev
Old link in the path for related figures.
Changed backend for receiving new link type.
> Fixed related figures behavior with new Streeetcode link

- Streetcode/Streetcode.XUnitTest/MediatRTests/Partners/CreatePartnerTest.cs
- Streetcode/Streetcode.XUnitTest/MediatRTests/Partners/DeletePartnerTest.cs
- Streetcode/Streetcode.XUnitTest/MediatRTests/Partners/GetAllPartnersTest.cs
- Streetcode/Streetcode.XUnitTest/MediatRTests/Partners/GetParnerByStreetcodeIdTest.cs
- Streetcode/Streetcode.XUnitTest/MediatRTests/Partners/GetPartnerByIdTest.cs
> Add tests for Partners

- Streetcode/Streetcode.BLL/Services/BlobStorageService/BlobEnvirovmentVariables.cs
- Streetcode/Streetcode.BLL/Services/BlobStorageService/BlobService.cs
- Streetcode/Streetcode.WebApi/Extensions/ConfigureHostBuilderExtensions.cs
- Streetcode/Streetcode.WebApi/Extensions/ServiceCollectionExtensions.cs
- Streetcode/Streetcode.WebApi/Program.cs
- Streetcode/Streetcode.WebApi/Properties/launchSettings.json
- Streetcode/Streetcode.WebApi/appsettings.json
> Blob storage env variables

- Streetcode/Streetcode.BLL/Mapping/Streetcode/CatalogProfile.cs
- Streetcode/Streetcode.BLL/MediatR/Streetcode/Streetcode/GetAllCatalog/GetAllStreetcodesCatalogHandler.cs
- Streetcode/Streetcode.BLL/MediatR/Streetcode/Streetcode/GetAllCatalog/GetAllStreetcodesCatalogQuery.cs
- Streetcode/Streetcode.BLL/MediatR/Streetcode/Streetcode/GetCount/GetStreetcodesCountHander.cs
- Streetcode/Streetcode.BLL/MediatR/Streetcode/Streetcode/GetCount/GetStreetcodesCountQuery.cs
- Streetcode/Streetcode.WebApi/Controllers/Streetcode/StreetcodeController.cs
dev
Needed to implement partial loading only one screen each time.
Created lazy loading for catalog page with pagination mechanism.
> Catalog. Backend pagination.

- Streetcode/Streetcode.BLL/DTO/AdditionalContent/Subtitles/SubtitleDTO.cs
- Streetcode/Streetcode.BLL/DTO/AdditionalContent/Subtitles/SubtitleStatusDTO.cs
- Streetcode/Streetcode.BLL/Mapping/AdditionalContent/SubtitleProfile.cs
- Streetcode/Streetcode.DAL/Entities/AdditionalContent/Subtitle.cs
- Streetcode/Streetcode.DAL/Enums/SubtitleStatus.cs
- Streetcode/Streetcode.DAL/Extensions/ModelBuilderExtensions.cs
- Streetcode/Streetcode.DAL/Persistence/Migrations/20230411194437_UpdateSubtitleColumn.Designer.cs
- Streetcode/Streetcode.DAL/Persistence/Migrations/20230411194437_UpdateSubtitleColumn.cs
- Streetcode/Streetcode.WebApi/Program.cs
- Streetcode/Streetcode.WebApi/appsettings.Local.json
- Streetcode/Streetcode.WebApi/appsettings.json
- Streetcode/Streetcode.XUnitTest/MediatRTests/AdditionalContent/AdditionalContentTests/SubtitleTests/GetAllSubtitlesRequestHandlerTests.cs
> Subtitle update

- Streetcode/Streetcode.DAL/Entities/AdditionalContent/Subtitle.cs
> Remove spaces under Id

- Streetcode/Streetcode.BLL/DTO/Toponyms/GetAllToponymsRequestDTO.cs
- Streetcode/Streetcode.BLL/DTO/Toponyms/GetAllToponymsResponseDTO.cs
- Streetcode/Streetcode.BLL/MediatR/AdditionalContent/Coordinate/Create/CreateCoordinateCommand.cs
- Streetcode/Streetcode.BLL/MediatR/AdditionalContent/Coordinate/Create/CreateCoordinateHandler.cs
- Streetcode/Streetcode.BLL/MediatR/AdditionalContent/Coordinate/Delete/DeleteCoordinateCommand.cs
- Streetcode/Streetcode.BLL/MediatR/AdditionalContent/Coordinate/Delete/DeleteCoordinateHandler.cs
- Streetcode/Streetcode.BLL/MediatR/AdditionalContent/Coordinate/Update/UpdateCoordinateCommand.cs
- Streetcode/Streetcode.BLL/MediatR/AdditionalContent/Coordinate/Update/UpdateCoordinateHanler.cs
- Streetcode/Streetcode.BLL/MediatR/Toponyms/GetAll/GetAllToponymsHandler.cs
- Streetcode/Streetcode.BLL/MediatR/Toponyms/GetAll/GetAllToponymsQuery.cs
- Streetcode/Streetcode.BLL/StreetCode.BLL.csproj
- Streetcode/Streetcode.DAL/StreetCode.DAL.csproj
- Streetcode/Streetcode.WebApi/Controllers/Toponyms/ToponymController.cs
- Streetcode/Streetcode.WebApi/Extensions/ServiceCollectionExtensions.cs
- Streetcode/Streetcode.WebApi/Program.cs
- Streetcode/Streetcode.WebApi/Streetcode.WebApi.csproj
- Streetcode/Streetcode.XIntegrationTest/Streetcode.XIntegrationTest.csproj
- Streetcode/Streetcode.XUnitTest/StreetCode.XUnitTest.csproj
- build/_build.csproj
>  toponyms and map admin finally finally 

- Streetcode/Streetcode.BLL/DTO/Payment/PaymentDTO.cs
- Streetcode/Streetcode.BLL/DTO/Payment/PaymentResponseDTO.cs
- Streetcode/Streetcode.BLL/Interfaces/Payment/IPaymentService.cs
- Streetcode/Streetcode.BLL/Mapping/Payment/PaymentProfile.cs
- Streetcode/Streetcode.BLL/MediatR/Payment/CreateInvoiceCommand.cs
- Streetcode/Streetcode.BLL/MediatR/Payment/CreateInvoiceHandler.cs
- Streetcode/Streetcode.BLL/Services/Payment/Exceptions/Error.cs
- Streetcode/Streetcode.BLL/Services/Payment/Exceptions/InvalidRequestParameterException.cs
- Streetcode/Streetcode.BLL/Services/Payment/Exceptions/InvalidTokenException.cs
- Streetcode/Streetcode.BLL/Services/Payment/Exceptions/MonobankException.cs
- Streetcode/Streetcode.BLL/Services/Payment/PaymentEnvirovmentVariables.cs
- Streetcode/Streetcode.BLL/Services/Payment/PaymentService.cs
- Streetcode/Streetcode.DAL/Entities/Payment/BasketOrder.cs
- Streetcode/Streetcode.DAL/Entities/Payment/Invoice.cs
- Streetcode/Streetcode.DAL/Entities/Payment/InvoiceInfo.cs
- Streetcode/Streetcode.DAL/Entities/Payment/MerchantPaymentInfo.cs
- Streetcode/Streetcode.DAL/Entities/Payment/SaveCardData.cs
- Streetcode/Streetcode.WebApi/Controllers/Payment/PaymentController.cs
- Streetcode/Streetcode.WebApi/Extensions/ConfigureHostBuilderExtensions.cs
- Streetcode/Streetcode.WebApi/Extensions/ServiceCollectionExtensions.cs
- Streetcode/Streetcode.WebApi/Program.cs
- Streetcode/Streetcode.WebApi/appsettings.json
- Streetcode/Streetcode.XUnitTest/Streetcode.XUnitTest.csproj
> Monobank_Api_Backend 

- Streetcode/Streetcode.BLL/Interfaces/BlobStorage/IBlobService.cs
- Streetcode/Streetcode.BLL/MediatR/Media/Audio/Update/UpdateAudioHandler.cs
- Streetcode/Streetcode.BLL/MediatR/Media/Image/Update/UpdateImageHandler.cs
- Streetcode/Streetcode.BLL/MediatR/Sources/SourceLink/GetCategoryById/GetCategoryByIdHandler.cs
- Streetcode/Streetcode.BLL/Services/BlobStorageService/BlobService.cs
- Streetcode/Streetcode.WebApi/Program.cs
- Streetcode/Streetcode.XUnitTest/MediatRTests/SourcesTests/GetCategoryByIdTest.cs
- Streetcode/Streetcode.XUnitTest/StreetCode.XUnitTest.csproj
> Blob all endpoints implementation

- Streetcode/Streetcode.BLL/MediatR/Streetcode/Term/Delete/DeleteTermHandler.cs
- Streetcode/Streetcode.BLL/MediatR/Streetcode/Term/Update/UpdateTermCommand.cs
- Streetcode/Streetcode.BLL/MediatR/Streetcode/Term/Update/UpdateTermHandler.cs
- Streetcode/Streetcode.WebApi/Controllers/Streetcode/TextContent/TermController.cs
- Streetcode/Streetcode.XUnitTest/MediatRTests/StreetCode/Terms/CreateTermHandlerTests.cs
- Streetcode/Streetcode.XUnitTest/MediatRTests/StreetCode/Terms/DeleteTermHendlerTests.cs
- Streetcode/Streetcode.XUnitTest/MediatRTests/StreetCode/Terms/UpdateTermHendlerTests.cs
- Streetcode/Streetcode.XUnitTest/MediatRTests/Timeline/HistoricalContextTests/GetAllHistoricalContextTest.cs
> Implement tests to Term and HistoricalContext

- Streetcode/Streetcode.BLL/DTO/Streetcode/Create/StreetcodeCreateDTO.cs
> added create for streetcode coordinates

- Streetcode/Streetcode.BLL/MediatR/AdditionalContent/Subtitle/GetByStreetcodeId/GetSubtitlesByStreetcodeIdHandler.cs
- Streetcode/Streetcode.BLL/MediatR/AdditionalContent/Subtitle/GetByStreetcodeId/GetSubtitlesByStreetcodeIdQuery.cs
- Streetcode/Streetcode.XUnitTest/MediatRTests/AdditionalContent/AdditionalContentTests/SubtitleTests/GetSubtitlesByStreetcodeIdRequestHandlerTests.cs
> FixSubtitle

- Streetcode/Streetcode.BLL/DTO/Streetcode/Create/StreetcodeCreateDTO.cs
- Streetcode/Streetcode.BLL/MediatR/Partners/Update/UpdatePartnerHandler.cs
- Streetcode/Streetcode.BLL/MediatR/Streetcode/Streetcode/GetByFilter/GetStreetcodeByFilterHandler.cs
> quickFixForSearch

- Streetcode/Streetcode.BLL/MediatR/Streetcode/Streetcode/Create/CreateStreetcodeHandler.cs
> fixCreateStreetcode

- Streetcode/Streetcode.BLL/Mapping/Media/Images/ImageProfile.cs
- Streetcode/Streetcode.BLL/Mapping/Sources/SourceLinkCategoryProfile.cs
- Streetcode/Streetcode.BLL/MediatR/Sources/SourceLinkCategory/Create/CreateCategoryHandler.cs
- Streetcode/Streetcode.BLL/MediatR/Sources/SourceLinkCategory/GetAll/GetAllCategoriesHandler.cs
- Streetcode/Streetcode.BLL/MediatR/Sources/SourceLinkCategory/GetAll/GetAllCategoriesQuery.cs
- Streetcode/Streetcode.BLL/MediatR/Sources/SourceLinkCategory/GetAll/IRequest.cs
- Streetcode/Streetcode.BLL/MediatR/Sources/SourceLinkCategory/Update/UpdateCategoryHandler.cs
- Streetcode/Streetcode.DAL/Entities/Sources/SourceLinkCategory.cs
- Streetcode/Streetcode.WebApi/Controllers/Media/Images/ImageController.cs
- Streetcode/Streetcode.WebApi/Controllers/Source/SourcesController.cs
> Created for fans admin back. Made new endpoints, Mapper and MediatR methods. 

- Streetcode/Streetcode.WebApi/Controllers/BaseApiController.cs
> fix Bad Request

- Streetcode/Streetcode.BLL/MediatR/Team/GetAllMain/GetAllMainTeamHandler.cs
- Streetcode/Streetcode.BLL/MediatR/Team/GetAllMain/GetAllMainTeamQuery.cs
- Streetcode/Streetcode.WebApi/Controllers/Team/TeamController.cs
> added new end-point for team

- Streetcode/Streetcode.BLL/DTO/Streetcode/StreetcodeMainPageDTO.cs
- Streetcode/Streetcode.BLL/Mapping/Streetcode/StreetcodeProfile.cs
- Streetcode/Streetcode.BLL/MediatR/Streetcode/Streetcode/GetAllMainPage/GetAllStreetcodesMainPageHandler.cs
- Streetcode/Streetcode.BLL/MediatR/Streetcode/Streetcode/GetAllMainPage/GetAllStreetcodesMainPageQuery.cs
- Streetcode/Streetcode.WebApi/Controllers/Streetcode/StreetcodeController.cs
> mainPage streetcode slider

- Streetcode/Streetcode.BLL/DTO/Streetcode/Create/StreetcodeCreateDTO.cs
- Streetcode/Streetcode.BLL/DTO/Transactions/TransactLinkDTO.cs
- Streetcode/Streetcode.BLL/MediatR/ResultVariations/NullResult.cs
- Streetcode/Streetcode.BLL/MediatR/Streetcode/Streetcode/Create/CreateStreetcodeHandler.cs
- Streetcode/Streetcode.BLL/MediatR/Transactions/TransactionLink/GetByStreetcodeId/GetTransactLinkByStreetcodeIdHandler.cs
- Streetcode/Streetcode.BLL/MediatR/Transactions/TransactionLink/GetByStreetcodeId/GetTransactLinkByStreetcodeIdQuery.cs
- Streetcode/Streetcode.WebApi/Controllers/BaseApiController.cs
- Streetcode/Streetcode.WebApi/Controllers/Transactions/TransactLinksController.cs
> fix streetcode create for ar effect

- Streetcode/Streetcode.BLL/DTO/Streetcode/Create/TextContent/TextCreateDTO.cs
- Streetcode/Streetcode.BLL/DTO/Streetcode/TextContent/TextDTO.cs
- Streetcode/Streetcode.DAL/Entities/Streetcode/TextContent/Text.cs
- Streetcode/Streetcode.DAL/Persistence/Migrations/20230521194343_Initial.Designer.cs
- Streetcode/Streetcode.DAL/Persistence/Migrations/20230521194343_Initial.cs
- Streetcode/Streetcode.DAL/Persistence/Migrations/StreetcodeDbContextModelSnapshot.cs
- Streetcode/Streetcode.DAL/Persistence/ScriptsMigration/DDL.sql
> Additional text fixed

- Streetcode/Streetcode.BLL/MediatR/Streetcode/Text/GetByStreetcodeId/GetTextByStreetcodeIdHandler.cs
- Streetcode/Streetcode.BLL/MediatR/Streetcode/Text/GetByStreetcodeId/GetTextByStreetcodeIdQuery.cs
> addNullResultToTextQuery

- Streetcode/Streetcode.BLL/DTO/News/NewsDTO.cs
- Streetcode/Streetcode.BLL/MediatR/Newss/Create/CreateNewsHandler.cs
- Streetcode/Streetcode.BLL/MediatR/Newss/SortedByDateTime/SortedByDateTimeHandler.cs
- Streetcode/Streetcode.BLL/MediatR/Newss/SortedByDateTime/SortedByDateTimeQuery.cs
- Streetcode/Streetcode.BLL/MediatR/Newss/Update/UpdateNewsHandler.cs
- Streetcode/Streetcode.BLL/MediatR/Sources/SourceLinkCategory/Delete/DeleteCategoryHandler.cs
- Streetcode/Streetcode.DAL/Entities/News/News.cs
- Streetcode/Streetcode.WebApi/Controllers/Newss/NewsController.cs
> Added new handler for sorted news by date time and removed unused usings

- Streetcode/Streetcode.BLL/MediatR/Newss/Update/UpdateNewsHandler.cs
Hot fix update method for news where we work out situation when we didn't have image and wanted to change new without adding new picture.
> check for image delete

- Streetcode/Streetcode.BLL/DTO/Streetcode/Update/StreetcodeUpdateDTO.cs
- Streetcode/Streetcode.BLL/DTO/Streetcode/Update/TextContent/HistoricalContextUpdateDTO.cs
- Streetcode/Streetcode.BLL/DTO/Streetcode/Update/TextContent/RelatedFigureUpdateDTO.cs
- Streetcode/Streetcode.BLL/DTO/Streetcode/Update/TextContent/TimelineItemUpdateDTO.cs
- Streetcode/Streetcode.BLL/DTO/Timeline/HistoricalContextDTO.cs
- Streetcode/Streetcode.BLL/DTO/Timeline/TimelineItemDTO.cs
- Streetcode/Streetcode.BLL/Mapping/Streetcode/StreetcodeProfile.cs
- Streetcode/Streetcode.BLL/Mapping/Timeline/HistoricalContextProfile.cs
- Streetcode/Streetcode.BLL/Mapping/Timeline/TimelineItemProfile.cs
- Streetcode/Streetcode.BLL/MediatR/Streetcode/Streetcode/Update/UpdateStreetcodeCommand.cs
- Streetcode/Streetcode.BLL/MediatR/Streetcode/Streetcode/Update/UpdateStreetcodeHandler.cs
- Streetcode/Streetcode.DAL/Repositories/Interfaces/Base/IRepositoryBase.cs
- Streetcode/Streetcode.DAL/Repositories/Realizations/Base/RepositoryBase.cs
- Streetcode/Streetcode.DAL/Repositories/Realizations/Base/RepositoryWrapper.cs
- Streetcode/Streetcode.WebApi/appsettings.Local.json
- Streetcode/Streetcode.WebApi/appsettings.json
> Streetcode update max

- Streetcode/Streetcode.BLL/DTO/Streetcode/Update/Interface/IChanged.cs
- Streetcode/Streetcode.BLL/DTO/Streetcode/Update/Media/VideoUpdateDTO.cs
- Streetcode/Streetcode.BLL/DTO/Streetcode/Update/TextContent/FactUpdateDTO.cs
- Streetcode/Streetcode.BLL/DTO/Streetcode/Update/TextContent/HistoricalContextUpdateDTO.cs
- Streetcode/Streetcode.BLL/DTO/Streetcode/Update/TextContent/RelatedFigureUpdateDTO.cs
- Streetcode/Streetcode.BLL/DTO/Streetcode/Update/TextContent/StreetcodeArtUpdateDTO.cs
- Streetcode/Streetcode.BLL/DTO/Streetcode/Update/TextContent/TimelineItemUpdateDTO.cs
- Streetcode/Streetcode.BLL/DTO/Timeline/TimelineItemDTO.cs
- Streetcode/Streetcode.BLL/MediatR/Streetcode/Streetcode/Update/UpdateStreetcodeHandler.cs
> changed from chanched to isChanged

- Streetcode/Streetcode.BLL/DTO/Streetcode/Update/PartnersUpdateDTO.cs
- Streetcode/Streetcode.BLL/DTO/Streetcode/Update/StreetcodeUpdateDTO.cs
- Streetcode/Streetcode.BLL/DTO/Streetcode/Update/TextContent/RelatedFigureUpdateDTO.cs
- Streetcode/Streetcode.BLL/Mapping/Partners/PartnerProfile.cs
- Streetcode/Streetcode.BLL/Mapping/Streetcode/StreetcodeProfile.cs
- Streetcode/Streetcode.BLL/MediatR/Streetcode/Streetcode/Update/UpdateStreetcodeHandler.cs
> Streetcode update partners and related figures

- Streetcode/Streetcode.BLL/DTO/Streetcode/Update/StreetcodeUpdateDTO.cs
- Streetcode/Streetcode.BLL/DTO/Streetcode/Update/Toponyms/StreetcodeToponymUpdateDTO.cs
- Streetcode/Streetcode.BLL/Mapping/Streetcode/StreetcodeProfile.cs
- Streetcode/Streetcode.BLL/Mapping/Toponyms/StreetcodeToponymProfile.cs
- Streetcode/Streetcode.BLL/Mapping/Toponyms/ToponymProfile.cs
- Streetcode/Streetcode.BLL/MediatR/Streetcode/Streetcode/Update/UpdateStreetcodeHandler.cs
- Streetcode/Streetcode.DAL/Repositories/Interfaces/Base/IRepositoryWrapper.cs
- Streetcode/Streetcode.DAL/Repositories/Interfaces/Toponyms/IStreetcodeToponymRepository.cs
- Streetcode/Streetcode.DAL/Repositories/Realizations/Base/RepositoryWrapper.cs
- Streetcode/Streetcode.DAL/Repositories/Realizations/Toponyms/StreetcodeToponymRepository.cs
> Streetcode update roman

- Streetcode/Streetcode.BLL/DTO/AdditionalContent/Subtitles/SubtitleDTO.cs
- Streetcode/Streetcode.BLL/DTO/Media/Art/StreetcodeArtDTO.cs
- Streetcode/Streetcode.BLL/DTO/Media/Video/VideoDTO.cs
- Streetcode/Streetcode.BLL/DTO/Media/Video/VideoUpdateDTO.cs
- Streetcode/Streetcode.BLL/DTO/Streetcode/Create/StreetcodeCreateDTO.cs
- Streetcode/Streetcode.BLL/DTO/Streetcode/RelatedFigure/RelatedFigureShortDTO.cs
- Streetcode/Streetcode.BLL/DTO/Streetcode/Update/StreetcodeUpdateDTO.cs
- Streetcode/Streetcode.BLL/Mapping/Media/VideoProfile.cs
- Streetcode/Streetcode.BLL/MediatR/Streetcode/Streetcode/Create/CreateStreetcodeHandler.cs
- Streetcode/Streetcode.BLL/MediatR/Streetcode/Streetcode/Update/UpdateStreetcodeCommand.cs
- Streetcode/Streetcode.BLL/MediatR/Streetcode/Streetcode/Update/UpdateStreetcodeHandler.cs
- Streetcode/Streetcode.BLL/MediatR/Timeline/TimelineItem/GetById/GetTimelineItemByIdHandler.cs
- Streetcode/Streetcode.DAL/Entities/Media/Images/Art.cs
- Streetcode/Streetcode.DAL/Persistence/Migrations/20230606195615_ArtTitle.Designer.cs
- Streetcode/Streetcode.DAL/Persistence/Migrations/20230606195615_ArtTitle.cs
- Streetcode/Streetcode.XUnitTest/MediatRTests/MediaTests/StreetcodeArtTests/GetStreetcodeArtByStreetcodeIdTest.cs
- Streetcode/Streetcode.XUnitTest/MediatRTests/Partners/GetParnerByStreetcodeIdTest.cs
> update arts + transaction

- Streetcode/Streetcode.BLL/MediatR/Streetcode/RelatedFigure/GetByStreetcodeId/GetRelatedFiguresByStreetcodeIdHandler.cs
- Streetcode/Streetcode.BLL/MediatR/Streetcode/RelatedFigure/GetByTagId/GetRelatedFiguresByTagIdHandler.cs
- Streetcode/Streetcode.BLL/MediatR/Streetcode/Streetcode/GetAllCatalog/GetAllStreetcodesCatalogHandler.cs
- Streetcode/Streetcode.BLL/MediatR/Streetcode/Streetcode/GetAllMainPage/GetAllStreetcodesMainPageHandler.cs
- Streetcode/Streetcode.BLL/MediatR/Streetcode/Streetcode/GetByFilter/GetStreetcodeByFilterHandler.cs
> Only published streetcodes display fix

- Streetcode/Streetcode.BLL/Services/BlobStorageService/BlobService.cs
- Streetcode/Streetcode.WebApi/Program.cs
> Feature blob storage cleaning

- Streetcode/Streetcode.BLL/DTO/AdditionalContent/Tag/StreetcodeTagUpdateDTO.cs
- Streetcode/Streetcode.BLL/DTO/Streetcode/Update/StreetcodeUpdateDTO.cs
- Streetcode/Streetcode.BLL/Mapping/AdditionalContent/TagProfile.cs
- Streetcode/Streetcode.BLL/MediatR/Streetcode/Streetcode/Update/UpdateStreetcodeHandler.cs
- Streetcode/Streetcode.DAL/Repositories/Interfaces/Base/IRepositoryBase.cs
- Streetcode/Streetcode.DAL/Repositories/Realizations/Base/RepositoryBase.cs
> StreetcodeTagIndex + Tag update

- Streetcode/Streetcode.BLL/DTO/Streetcode/Update/StreetcodeUpdateDTO.cs
- Streetcode/Streetcode.BLL/MediatR/Streetcode/Streetcode/Update/UpdateStreetcodeHandler.cs
> generic update

- Streetcode/Streetcode.BLL/MediatR/Toponyms/GetByStreetcodeId/GetToponymsByStreetcodeIdHandler.cs
- Streetcode/Streetcode.DAL/Entities/Streetcode/StreetcodeContent.cs
- Streetcode/Streetcode.DAL/Persistence/Migrations/20230609102603_Initial.Designer.cs
- Streetcode/Streetcode.DAL/Persistence/Migrations/20230609102603_Initial.cs
- Streetcode/Streetcode.DAL/Persistence/Migrations/StreetcodeDbContextModelSnapshot.cs
- Streetcode/Streetcode.DAL/Persistence/ScriptsMigration/DDL.sql
> fixed toponyms and added unique for index

- Streetcode/Streetcode.BLL/DTO/AdditionalContent/Coordinates/Update/StreetcodeCoordinateUpdateDTO.cs
- Streetcode/Streetcode.BLL/DTO/Analytics/Update/StatisticRecordUpdateDTO.cs
- Streetcode/Streetcode.BLL/DTO/Sources/Update/StreetcodeCategoryContentUpdateDTO.cs
- Streetcode/Streetcode.BLL/DTO/Streetcode/Update/StreetcodeUpdateDTO.cs
- Streetcode/Streetcode.BLL/Mapping/AdditionalContent/Coordinates/StreetcodeCoordinateProfile.cs
- Streetcode/Streetcode.BLL/Mapping/Analytics/StatisticRecordProfile.cs
- Streetcode/Streetcode.BLL/Mapping/Sources/StreetcodeCategoryContentProfile.cs
- Streetcode/Streetcode.BLL/Mapping/Streetcode/StreetcodeProfile.cs
- Streetcode/Streetcode.BLL/MediatR/Streetcode/Streetcode/Update/StreetcodeRecordUpdateDTO.cs
- Streetcode/Streetcode.BLL/MediatR/Streetcode/Streetcode/Update/UpdateStreetcodeHandler.cs
> [Update] Streetcode update coordinates and category content

- Streetcode/Streetcode.BLL/DTO/News/NewsDTOWithURLs.cs
- Streetcode/Streetcode.BLL/DTO/News/RandomNewsDTO.cs
- Streetcode/Streetcode.BLL/MediatR/Newss/GetNewsAndLinksByUrl/GetNewsAndLinksByUrlHandler.cs
- Streetcode/Streetcode.BLL/MediatR/Newss/GetNewsAndLinksByUrl/GetNewsAndLinksByUrlQuery.cs
- Streetcode/Streetcode.WebApi/Controllers/Newss/NewsController.cs
> Created news API for newsPage optimization

- Streetcode/Streetcode.BLL/MediatR/Team/Position/Create/CreatePositionHandler.cs
- Streetcode/Streetcode.XUnitTest/MediatRTests/Team/Position/CreatePositionTest.cs
- Streetcode/Streetcode.XUnitTest/MediatRTests/Team/Position/CreatePositionTests.cs
- Streetcode/Streetcode.XUnitTest/MediatRTests/Team/Position/GetAllPositionTest.cs
- Streetcode/Streetcode.XUnitTest/MediatRTests/Team/TeamMemberLink/CreateTeamMembersLinkTest.cs
- Streetcode/Streetcode.XUnitTest/MediatRTests/Team/TeamMemberLink/GetAllTeamMembersLinksTest.cs
> Unit tests for team link and positions endpoints

- Streetcode/Streetcode.XUnitTest/MediatRTests/Newss/GetNewsByIdTest.cs
- Streetcode/Streetcode.XUnitTest/MediatRTests/Newss/GetNewsByUrlTest.cs
- Streetcode/Streetcode.XUnitTest/MediatRTests/Team/CreateTeamTest.cs
- Streetcode/Streetcode.XUnitTest/MediatRTests/Team/UpdateTeamTest.cs
> Added unit tests for Team and News mediatrs

- Streetcode/Streetcode.XUnitTest/MediatRTests/Media/Audio/GetAllAudioHandlerTests.cs
- Streetcode/Streetcode.XUnitTest/MediatRTests/Newss/SortedByDateTimeHandlerTest.cs
- Streetcode/Streetcode.XUnitTest/MediatRTests/StreetCode/Terms/CreateTermHandlerTests.cs
Fix:
- ../Streetcode/Term/Create
- ../Media/Audio/GetAll
Create:
- ../Newss/SortedByDateTime
dev
ToDo
ToDo
ToDo
> UnitTest Fix and create

- Streetcode/Streetcode.XUnitTest/MediatRTests/News/CreateNewsTest.cs
- Streetcode/Streetcode.XUnitTest/MediatRTests/News/DeleteNewsTest.cs
- Streetcode/Streetcode.XUnitTest/MediatRTests/News/GetAllNewsTest.cs
- Streetcode/Streetcode.XUnitTest/MediatRTests/News/UpdateNewsTest.cs
> #272 Tests for news

- Streetcode/Streetcode.XUnitTest/MediatRTests/Teams/DeleteTeamTest.cs
- Streetcode/Streetcode.XUnitTest/MediatRTests/Teams/GetAllTeamsTest.cs
- Streetcode/Streetcode.XUnitTest/MediatRTests/Teams/GetByIdTeamTest.cs
> Unit tests for "Team" MediatR.

- Streetcode/Streetcode.XUnitTest/MediatRTests/Newss/CreateNewsTest.cs
- Streetcode/Streetcode.XUnitTest/MediatRTests/Newss/DeleteNewsTest.cs
- Streetcode/Streetcode.XUnitTest/MediatRTests/Newss/GetAllNewsTest.cs
- Streetcode/Streetcode.XUnitTest/MediatRTests/Newss/UpdateNewsTest.cs
> Delete folder "News" and move tests to "Newss"

- Streetcode/Streetcode.BLL/DTO/Partners/Create/CreatePartnerDTO.cs
- Streetcode/Streetcode.BLL/DTO/Partners/Create/CreatePartnerSourceLinkDTO.cs
- Streetcode/Streetcode.BLL/DTO/Partners/PartnerDTO.cs
- Streetcode/Streetcode.BLL/Mapping/Partners/PartnerSourceLinkProfile.cs
- Streetcode/Streetcode.DAL/Entities/Partners/Partner.cs
- Streetcode/Streetcode.DAL/Entities/Partners/PartnerSourceLink.cs
- Streetcode/Streetcode.DAL/Persistence/Migrations/20230703154732_UpdatePartnerModel.Designer.cs
- Streetcode/Streetcode.DAL/Persistence/Migrations/20230703154732_UpdatePartnerModel.cs
- Streetcode/Streetcode.WebApi/Extensions/SeedingLocalExtension.cs
Updated the partner model. Made TargetUrl nullable. Removed an unnecessary field(title) in a link to a partner's social network. Updated the database.
> updated partner model

- Streetcode/Streetcode.BLL/DTO/Streetcode/Create/StreetcodeCreateDTO.cs
- Streetcode/Streetcode.BLL/DTO/Streetcode/Update/StreetcodeUpdateDTO.cs
- Streetcode/Streetcode.BLL/Mapping/Streetcode/RelatedFigureProfile.cs
- Streetcode/Streetcode.BLL/MediatR/Media/Image/GetByStreetcodeId/GetImageByStreetcodeIdHandler.cs
- Streetcode/Streetcode.BLL/MediatR/Streetcode/RelatedFigure/GetByStreetcodeId/GetRelatedFiguresByStreetcodeIdHandler.cs
- Streetcode/Streetcode.BLL/MediatR/Streetcode/Streetcode/Create/CreateStreetcodeHandler.cs
- Streetcode/Streetcode.BLL/MediatR/Streetcode/Streetcode/Update/UpdateStreetcodeHandler.cs
- Streetcode/Streetcode.DAL/Enums/ImageAssigment.cs
> Nk 446 streetcode photo

- Streetcode/Streetcode.BLL/DTO/Streetcode/Update/StreetcodeUpdateDTO.cs
> fix publish and draft date 

- Streetcode/Streetcode.XUnitTest/MediatRTests/StreetCode/Streetcode/GetAllStreetcodesHandlerTests.cs
> Added tests for FindStreetcodesWithMatchTitle() FindSortedStreetcodes() FindFilteredStreetcodes() in GetAllStreetcodehandler

- Streetcode/Streetcode.BLL/MediatR/Media/Audio/GetByStreetcodeId/GetAudioByStreetcodeIdQueryHandler.cs
- Streetcode/Streetcode.BLL/MediatR/Streetcode/Text/GetByStreetcodeId/GetTextByStreetcodeIdHandler.cs
> fix text and audio

- Streetcode/Streetcode.BLL/MediatR/Streetcode/RelatedFigure/GetAllPublished/GetAllPublishedQuery.cs
- Streetcode/Streetcode.BLL/MediatR/Streetcode/Streetcode/GetAllPublished/GetAllPublishedHandler.cs
- Streetcode/Streetcode.BLL/MediatR/Streetcode/Streetcode/GetAllPublished/GetAllPublishedQuery.cs
- Streetcode/Streetcode.WebApi/Controllers/Streetcode/RelatedFigureController.cs
- Streetcode/Streetcode.WebApi/Controllers/Streetcode/StreetcodeController.cs
> fix related figures

- Streetcode/Streetcode.BLL/DTO/Streetcode/Create/StreetcodeCreateDTO.cs
- Streetcode/Streetcode.BLL/DTO/Streetcode/StreetcodeDTO.cs
- Streetcode/Streetcode.BLL/DTO/Streetcode/Update/StreetcodeUpdateDTO.cs
- Streetcode/Streetcode.BLL/Mapping/Streetcode/StreetcodeProfile.cs
- Streetcode/Streetcode.BLL/MediatR/Streetcode/Streetcode/Create/CreateStreetcodeHandler.cs
- Streetcode/Streetcode.BLL/MediatR/Streetcode/Streetcode/Update/UpdateStreetcodeHandler.cs
- Streetcode/Streetcode.DAL/Enums/StreetcodeTypeDiscriminators.cs
- Streetcode/Streetcode.DAL/Persistence/StreetcodeDbContext.cs
> 404 update create streetcode nk

- Streetcode/Streetcode.BLL/MediatR/Streetcode/Streetcode/Delete/DeleteStreetcodeHandler.cs
- Streetcode/Streetcode.XUnitTest/MediatRTests/StreetCode/Streetcode/DeleteStreetcodeHandlerTests.cs
[* [Main JIRA ticket](https://jira.softserve.academy/secure/RapidBoard.jspa?rapidView=id)](https://github.com/ita-social-projects/StreetCode_Client/issues/399)
> fix streetcode deleting

- Streetcode/Streetcode.BLL/DTO/Streetcode/Catalog/CatalogItem.cs
- Streetcode/Streetcode.BLL/Mapping/Streetcode/Catalog/CatalogItemProfile.cs
- Streetcode/Streetcode.BLL/MediatR/Streetcode/Streetcode/GetAllCatalog/GetAllStreetcodesCatalogHandler.cs
- Streetcode/Streetcode.BLL/MediatR/Streetcode/Streetcode/GetAllCatalog/GetAllStreetcodesCatalogQuery.cs
> Fix catalog streetcodes displaying images

- Streetcode/Streetcode.BLL/MediatR/AdditionalContent/Tag/GetByStreetcodeId/GetTagByStreetcodeIdHandler.cs
> Fix tags order

- Streetcode/Streetcode.BLL/MediatR/Streetcode/Text/GetByStreetcodeId/GetTextByStreetcodeIdHandler.cs
- Streetcode/Streetcode.BLL/Services/Text/AddTermsToTextService.cs
> fix text load

- Streetcode/Streetcode.BLL/DTO/Streetcode/Update/StreetcodeUpdateDTO.cs
- Streetcode/Streetcode.BLL/DTO/Transactions/TransactionLinkUpdateDTO.cs
- Streetcode/Streetcode.BLL/Mapping/Transactions/TransactionLinkProfile.cs
- Streetcode/Streetcode.BLL/MediatR/Streetcode/Streetcode/Update/UpdateStreetcodeHandler.cs
dev
#515
Editing of the AR link was not working on admin page.
Working functionality.
Edit the ar link.
> 515 Admin AR Editing

- Streetcode/Streetcode.BLL/MediatR/Jobs/GetById/GetJobByIdHandler.cs
- Streetcode/Streetcode.BLL/MediatR/Jobs/GetById/GetJobByIdQuery.cs
- Streetcode/Streetcode.WebApi/Controllers/Jobs/JobController.cs
> Added controller GetJobById

- Streetcode/Streetcode.WebApi/Extensions/ConfigureHostBuilderExtensions.cs
- Streetcode/Streetcode.WebApi/Program.cs
- Streetcode/Streetcode.WebApi/Streetcode.WebApi.csproj
- Streetcode/Streetcode.WebApi/appsettings.json
Middleware to limit amount of incomung requests.
ToDo
ToDo
ToDo
> Rate limiting middleware

- Streetcode/Streetcode.BLL/Services/Text/AddTermsToTextService.cs
> fix related term

- Streetcode/Streetcode.BLL/DTO/Team/TeamMemberDTO.cs
- Streetcode/Streetcode.DAL/Entities/Team/TeamMember.cs
- Streetcode/Streetcode.WebApi/Extensions/SeedingLocalExtension.cs
Reverts ita-social-projects/StreetCode#621
> Revert "team fix"

- Streetcode/Streetcode.BLL/DTO/Team/TeamMemberDTO.cs
- Streetcode/Streetcode.DAL/Entities/Team/TeamMember.cs
- Streetcode/Streetcode.WebApi/Extensions/SeedingLocalExtension.cs
Reverts ita-social-projects/StreetCode#627
> Revert "Revert "team fix""

- Streetcode/Streetcode.BLL/MediatR/Streetcode/Streetcode/GetAllMainPage/GetAllStreetcodesMainPageHandler.cs
> random output on main page

- Streetcode/Streetcode.BLL/DTO/Team/TeamMemberDTO.cs
- Streetcode/Streetcode.BLL/MediatR/Team/GetNamePosition/GetTickerStringHandler.cs
- Streetcode/Streetcode.BLL/MediatR/Team/GetNamePosition/GetTickerStringQuery.cs
- Streetcode/Streetcode.WebApi/Controllers/Team/TickerStringController.cs
> added handler for TickerString and fixed team create

- Streetcode/Streetcode.BLL/Mapping/Streetcode/StreetcodeProfile.cs
- Streetcode/Streetcode.BLL/MediatR/Streetcode/Streetcode/GetAllMainPage/GetAllStreetcodesMainPageHandler.cs
> black and white fix

- Streetcode/Streetcode.BLL/MediatR/Streetcode/RelatedFigure/GetByTagId/GetRelatedFiguresByTagIdHandler.cs
> image on the tag fix

- Streetcode/Streetcode.WebApi/Controllers/Media/AudioController.cs
- Streetcode/Streetcode.WebApi/Controllers/Media/Images/ArtController.cs
- Streetcode/Streetcode.WebApi/Controllers/Media/Images/ImageController.cs
- Streetcode/Streetcode.WebApi/Controllers/Media/Images/StreetcodeArtController.cs
- Streetcode/Streetcode.WebApi/Extensions/ServiceCollectionExtensions.cs
- Streetcode/Streetcode.WebApi/Program.cs
> Response caching

- Streetcode/Streetcode.WebApi/appsettings.json
> Fix email credentials

- Streetcode/Streetcode.WebApi/Controllers/Media/AudioController.cs
- Streetcode/Streetcode.WebApi/Controllers/Media/Images/ArtController.cs
- Streetcode/Streetcode.WebApi/Controllers/Media/Images/ImageController.cs
- Streetcode/Streetcode.WebApi/Controllers/Media/Images/StreetcodeArtController.cs
- Streetcode/Streetcode.WebApi/Controllers/Streetcode/TextContent/TextController.cs
> Cashing for andrii

- Streetcode/Streetcode.BLL/MediatR/Partners/GetByIsKeyPartner/GetPartnersByIsKeyPartnerHandler.cs
- Streetcode/Streetcode.BLL/MediatR/Partners/GetByIsKeyPartner/GetPartnersByIsKeyPartnerQuery.cs
- Streetcode/Streetcode.WebApi/Controllers/Partners/PartnersController.cs
> add GetPartnersByIsKeyPartner method

- Streetcode/Streetcode.BLL/MediatR/Streetcode/Text/GetByStreetcodeId/GetTextByStreetcodeIdHandler.cs
- Streetcode/Streetcode.BLL/Services/CacheService/CacheService.cs
Reverts ita-social-projects/StreetCode#720
> Revert "1"

- build/Targets/BaseBuild.cs
- build/_build.csproj
dev
add gitversions to nuke build
ToDo
ToDo
ToDo
> add gitversions to nuke build

- Streetcode/Streetcode.BLL/Interfaces/Audio/IAudioService.cs
- Streetcode/Streetcode.BLL/Services/AudioService/AudioService.cs
- Streetcode/Streetcode.BLL/Services/Logging/LoggerService.cs
- Streetcode/Streetcode.WebApi/Extensions/RecurringJobExtensions.cs
- Streetcode/Streetcode.WebApi/Extensions/ServiceCollectionExtensions.cs
- Streetcode/Streetcode.WebApi/Hangfire/HangfireDashboardAuthorizationFilter.cs
- Streetcode/Streetcode.WebApi/Program.cs
- Streetcode/Streetcode.WebApi/appsettings.Local.json
- Streetcode/Streetcode.WebApi/appsettings.Production.json
- Streetcode/Streetcode.WebApi/appsettings.json
Add unused audio deleting
[WARNING] need to update frequency before merging
- DONE
> Add recurring job

- Streetcode/Streetcode.BLL/MediatR/AdditionalContent/Tag/GetByStreetcodeId/GetTagByStreetcodeIdHandler.cs
- Streetcode/Streetcode.BLL/MediatR/Streetcode/Streetcode/GetById/GetStreetcodeByIdHandler.cs
- Streetcode/Streetcode.BLL/MediatR/Streetcode/Streetcode/GetByTransliterationUrl/GetStreetcodeByTransliterationUrlHandler.cs
> Streetcode tags ordering by index

- Streetcode/Streetcode.BLL/Interfaces/Audio/IAudioService.cs
- Streetcode/Streetcode.BLL/Services/AudioService/AudioService.cs
- Streetcode/Streetcode.WebApi/Extensions/RecurringJobExtensions.cs
minor styling fixes of recurring audio job
> fix comments all except timezone:

- Streetcode/Streetcode.DAL/Entities/Jobs/Job.cs
dev
Make salary not required
ToDo
ToDo
ToDo
> fix reqiured salary

- Streetcode/Streetcode.DAL/Entities/Jobs/Job.cs
Reverts ita-social-projects/StreetCode#734
> Revert "fix reqiured salary"

- Streetcode/Streetcode.BLL/Interfaces/Image/IImageService.cs
- Streetcode/Streetcode.BLL/Services/ImageService/ImageService.cs
- Streetcode/Streetcode.WebApi/Extensions/RecurringJobExtensions.cs
- Streetcode/Streetcode.WebApi/Extensions/ServiceCollectionExtensions.cs
- Streetcode/Streetcode.WebApi/Program.cs
- Streetcode/Streetcode.WebApi/appsettings.Production.json
- Streetcode/Streetcode.WebApi/appsettings.json
> job for deleting unused images

- Streetcode/Streetcode.BLL/DTO/Streetcode/StreetcodeFilterResultDTO.cs
- Streetcode/Streetcode.BLL/MediatR/Streetcode/Streetcode/GetByFilter/GetStreetcodeByFilterHandler.cs
update GetStreetcodeByFilter (add fact Id and timeline Id to the response)
dev
ToDo
ToDo
ToDo
> Fix searching

- Jenkinsfile
add nuke build into jenkins
dev
ToDo
ToDo
ToDo
> add nuke build into jenkins

- Streetcode/Streetcode.BLL/MediatR/Streetcode/Streetcode/GetPageMainPage/GetPageOfStreetcodesMainPageHandler.cs
- Streetcode/Streetcode.BLL/MediatR/Streetcode/Streetcode/GetPageMainPage/GetPageOfStreetcodesMainPageQuery.cs
- Streetcode/Streetcode.BLL/Util/IEnumerableExtensions.cs
- Streetcode/Streetcode.BLL/Util/IQueryableExtensions.cs
- Streetcode/Streetcode.WebApi/Controllers/Streetcode/StreetcodeController.cs
> getting streetcodes on main page with pagination/back

- Streetcode/Streetcode.BLL/HealthChecks/HealthChecksExtension.cs
- Streetcode/Streetcode.BLL/HealthChecks/HealthChecksOptions.cs
- Streetcode/Streetcode.BLL/HealthChecks/LivenessHealthChecks.cs
- Streetcode/Streetcode.BLL/HealthChecks/MemoryMetrics/MemoryMetrics.cs
- Streetcode/Streetcode.BLL/HealthChecks/MemoryMetrics/MemoryMetricsClient.cs
- Streetcode/Streetcode.BLL/HealthChecks/ReadinessHealthChecks.cs
- Streetcode/Streetcode.BLL/HealthChecks/StartUpHealthChecks.cs
- Streetcode/Streetcode.BLL/Streetcode.BLL.csproj
- Streetcode/Streetcode.WebApi/Extensions/ConfigureHostBuilderExtensions.cs
- Streetcode/Streetcode.WebApi/Extensions/ServiceCollectionExtensions.cs
- Streetcode/Streetcode.WebApi/Program.cs
- Streetcode/Streetcode.WebApi/appsettings.json
user story link: https://github.com/ita-social-projects/StreetCode/issues/278
> move all changes from outdated health check pull request

- .github/workflows/build.yml
- Jenkinsfile
- Streetcode/Streetcode.WebApi/Program.cs
Reverts ita-social-projects/StreetCode#751
> Revert "Fix sonarcloud"

- Streetcode/Streetcode.WebApi/Program.cs
Reverts ita-social-projects/StreetCode#802
> Revert "Fix https"

- Streetcode/Streetcode.WebApi/Controllers/BaseApiController.cs
API project should be able to build
> remove trailing comma

- Streetcode/Streetcode.WebApi/Controllers/BaseApiController.cs
- Streetcode/Streetcode.WebApi/Program.cs
> add swagger for stage and local

- Streetcode/Streetcode.BLL/MediatR/Streetcode/Streetcode/GetCount/GetStreetcodesCountHander.cs
- Streetcode/Streetcode.BLL/MediatR/Streetcode/Streetcode/GetCount/GetStreetcodesCountQuery.cs
- Streetcode/Streetcode.WebApi/Controllers/Streetcode/StreetcodeController.cs
> Stage update (#908)

- Streetcode/Streetcode.DAL/Entities/Streetcode/StreetcodeContent.cs
- Streetcode/Streetcode.DAL/Persistence/Migrations/20231130202258_DatestringLength.Designer.cs
- Streetcode/Streetcode.DAL/Persistence/Migrations/20231130202258_DatestringLength.cs
> Changed datestring max length to 100 instead of 50

- Streetcode/Streetcode.DAL/Entities/Streetcode/StreetcodeContent.cs
- Streetcode/Streetcode.DAL/Persistence/Migrations/20231130202258_DatestringLength.Designer.cs
- Streetcode/Streetcode.DAL/Persistence/Migrations/20231130202258_DatestringLength.cs
> Update master (#901)

- Streetcode/Streetcode.WebApi/Program.cs
> fix swagger for stage

- Streetcode/Streetcode.BLL/MediatR/Newss/GetNewsAndLinksByUrl/GetNewsAndLinksByUrlHandler.cs
- Streetcode/Streetcode.BLL/MediatR/Streetcode/Streetcode/GetCount/GetStreetcodesCountHander.cs
- Streetcode/Streetcode.BLL/MediatR/Streetcode/Streetcode/GetCount/GetStreetcodesCountQuery.cs
- Streetcode/Streetcode.DAL/Entities/Streetcode/StreetcodeContent.cs
- Streetcode/Streetcode.DAL/Persistence/Migrations/20231130202258_DatestringLength.Designer.cs
- Streetcode/Streetcode.DAL/Persistence/Migrations/20231130202258_DatestringLength.cs
- Streetcode/Streetcode.WebApi/Controllers/BaseApiController.cs
- Streetcode/Streetcode.WebApi/Controllers/Streetcode/StreetcodeController.cs
- Streetcode/Streetcode.WebApi/Program.cs
> merge master to deve;op

- README.md
Add instructions on database seeding in  'Setup' section in README.md
+ Previous 'Setup' view:
+ Current 'Setup' view:
> Update 'Setup' section in README.md

- Streetcode/Streetcode.DAL/Entities/Jobs/Job.cs
- Streetcode/Streetcode.DAL/Persistence/Migrations/20240104113247_JobsDescriptionLength.Designer.cs
- Streetcode/Streetcode.DAL/Persistence/Migrations/20240104113247_JobsDescriptionLength.cs
> Changed job description length limit

- Streetcode/Streetcode.XIntegrationTest/ControllerTests/Streetcode/Update/StreetcodeUpdateControllerTests.cs
- Streetcode/Streetcode.XIntegrationTest/ControllerTests/Utils/BeforeAndAfterTestAtribute/Streetcode/ExtractTestUpdateStreetcode.cs
> Suggested changes to 'Integration tests streetcode update' pull request

- Dockerfile
> test fix swagger

- Dockerfile
> revert swagger

- Dockerfile
> fix swagger

- Streetcode/Streetcode.BLL/MediatR/Streetcode/Streetcode/GetByFilter/GetStreetcodeByFilterHandler.cs
Try to search run with string that has a lot of spaces before or after text
**Example**
```
Тарас      
````
> trim query before getting from db

- Streetcode/Streetcode.BLL/Services/AudioService/AudioService.cs
How to check:
change string in appsettings to "*/2 * * * *" for audio cleaning (in that way the job will run every 2 minutes)
add an audio to streetcode and delete it (without saving a streetcode)
add another audio to streetcode and save streetcode with it
when the job will run, you should see a log that one audio was deleted
> optimize query

- Streetcode/Streetcode.WebApi/appsettings.Production.json
- Streetcode/Streetcode.WebApi/appsettings.json
How to check - replace `3` digit in `0 3 * * *` string( appsettings) to the nearest hour and check if the job is executed at the hour (logs of the job should be present in terminal)
> adjust time from every minute from 3 to 4 am -> one time at 3 am

- Streetcode/Streetcode.BLL/DTO/Sources/StreetcodeCategoryContentDTO.cs
- Streetcode/Streetcode.DAL/Entities/Sources/StreetcodeCategoryContent.cs
- Streetcode/Streetcode.DAL/Persistence/Migrations/20240122161255_ForFansLength.Designer.cs
- Streetcode/Streetcode.DAL/Persistence/Migrations/20240122161255_ForFansLength.cs
- Streetcode/Streetcode.DAL/Persistence/Migrations/StreetcodeDbContextModelSnapshot.cs
> Hot max length fix

- Streetcode/Streetcode.BLL/Services/Email/EmailService.cs
> add logger to the Email service

- Streetcode/Streetcode.WebApi/appsettings.Production.json
> change email

- Streetcode/Streetcode.BLL/Services/Email/EmailService.cs
> feat: add logging to smtp client

- Jenkinsfile
* [Ticket](https://github.com/orgs/ita-social-projects/projects/21/views/10?sliceBy%5Bvalue%5D=MaksymukNatalia&pane=issue&itemId=45936766)
Remake build steps to Jenkinsfile. Now Jenkinsfile provide completed CI/CD.
> Add  new Jenkinsfile with versioning

- Jenkinsfile
* [Task url ](https://github.com/ita-social-projects/StreetCode/issues/888)
ToDo
1 add pull from * [New DevOps github](https://github.com/ita-social-projects/Streetcode-DevOps)
2 change script commands in steps/
> Add pull new docker-compose file and fix error in  Jenkinsfile

- Streetcode/Streetcode.BLL/MediatR/Streetcode/Streetcode/GetPageMainPage/GetPageOfStreetcodesMainPageHandler.cs
> sorted 10 last streetcodes in desc order, removed random shuffle

- Streetcode/Streetcode.BLL/MediatR/Streetcode/Streetcode/Create/CreateStreetcodeHandler.cs
dev
* [Main Github ticket](https://github.com/ita-social-projects/StreetCode/issues/1149#issue-2118700859)
empty ImageDetailes field caused streetcode to appear without photos
awaited task which was managing this logic
> feat: fixed issue with imageDetails accepting empty data

- Streetcode/Streetcode.BLL/DTO/Media/Audio/AudioDTO.cs
- Streetcode/Streetcode.BLL/MediatR/Media/Audio/Create/CreateAudioHandler.cs
- Streetcode/Streetcode.BLL/MediatR/Media/Audio/Update/UpdateAudioHandler.cs
- Streetcode/Streetcode.XUnitTest/MediatRTests/Media/Audio/CreateAudioTests.cs
- Streetcode/Streetcode.XUnitTest/MediatRTests/Media/Audio/UpdateAudioTests.cs
Added audioDTO validation to make it impossible to save an audio without all required fields
> Add audio validation

- Streetcode/Streetcode.BLL/MediatR/Sources/SourceLinkCategory/GetAll/GetAllCategoriesHandler.cs
dev
* [Main ticket](https://github.com/ita-social-projects/StreetCode/issues/1545)
The list of created categories is not sorted alphabetically
Add alphabetical sorting of categories
ToDo
> Add alphabetical sorting of categories

- Streetcode/Streetcode.BLL/DTO/Email/EmailDTO.cs
- Streetcode/Streetcode.BLL/MediatR/Email/SendEmailHandler.cs
- Streetcode/Streetcode.BLL/Services/Email/EmailService.cs
- Streetcode/Streetcode.DAL/Entities/AdditionalContent/Email/Message.cs
* Ticket ita-social-projects/StreetCode#976
* [frontend part](https://github.com/ita-social-projects/StreetCode_Client/pull/1390)
Add note to email, where did it come from Contacts page or Partners Page
- Source property added to EmailDTO
- Source added while sending emails
> Source added to Email message

- .github/PULL_REQUEST_TEMPLATE/develop.md
Link to the corresponding GitHub board ticket: [#1660](https://github.com/orgs/ita-social-projects/projects/21/views/1?filterQuery=&pane=issue&itemId=75195386)
This pull request focuses on reviewing and standardizing the pull request templates for the back-end repository. The purpose of the change is to reflect the team's current needs by removing outdated JIRA ticket references and adding a new section for linking to GitHub board tickets.
- Removed JIRA ticket information from the pull request templates.
- Added a new section to link to relevant tickets on the GitHub board.
- Aligned the templates with the team's updated workflow and project requirements.
---
> updated develop.md

- Streetcode/Streetcode.BLL/MediatR/Streetcode/Streetcode/GetByFilter/GetStreetcodeByFilterHandler.cs
- Streetcode/Streetcode.XUnitTest/MediatRTests/StreetCode/Streetcode/GetStreetcodeByFilterHandlerTests.cs
- [Main GitHub ticket](https://github.com/ita-social-projects/StreetCode/issues/1683)
- The script needed refactoring and writing tests for it.
1. Refactoring of `GetStreetcodeByFilterHandler.cs` script has been done.
2. Tests for `Handle `method `GetStreetcodeByFilterHandler.cs`  were written.
> Rafactoring and tests for `GetStreetcodeByFilterHandler.cs`

- Streetcode/Streetcode.WebApi/appsettings.Staging.json
* [Main Github ticket](https://github.com/ita-social-projects/StreetCode/issues/1787)
Сreate an additional email for the stage to be able to test functions with sending messages to the customer from users
> Feature/issue-1787: update email

- Dockerfile.dbupdate
> add dockerfile.dbupdate

- Jenkinsfile
> comment prod stage

- Streetcode/Streetcode.BLL/Resources/SharedResource.FieldNamesSharedResource.en-US.resx
- Streetcode/Streetcode.BLL/Resources/SharedResource.FieldNamesSharedResource.uk-UA.resx
- Streetcode/Streetcode.BLL/Validators/Payment/CreateInvoiceCommandValidator.cs
- Streetcode/Streetcode.XUnitTest/Validators/Payment/CreateInvoiceCommandValidatorTests.cs
> Ticket#1313 (fixed improper localized message)

- Streetcode/Streetcode.BLL/Resources/SharedResource.FailedToValidateSharedResource.en-US.resx
- Streetcode/Streetcode.BLL/Resources/SharedResource.FailedToValidateSharedResource.uk-UA.resx
* [Github ticket](https://github.com/ita-social-projects/StreetCode/issues/2040)
When adding a link different from the selected social network, an incorrect error is displayed. 
Changed validation messages so they match expected result
> changed validation messages

- Streetcode/Streetcode.BLL/DTO/AdditionalContent/Tag/TagDTO.cs
- Streetcode/Streetcode.BLL/Mapping/AdditionalContent/TagProfile.cs
* [Github ticket #2025](https://github.com/ita-social-projects/StreetCode/issues/2025)
* [Github ticket #2026](https://github.com/ita-social-projects/StreetCode/issues/2026)
* [Github ticket #2028](https://github.com/ita-social-projects/StreetCode/issues/2028)
* [Github ticket #2029](https://github.com/ita-social-projects/StreetCode/issues/2029)
The presence of extra information in response body for tag endpoints.
Removed extra field from Tag DTO.
> Removed redundant information in tag endpoints responses.

- Streetcode/Streetcode.BLL/Validators/Partners/CreatePartnerValidator.cs
- Streetcode/Streetcode.XUnitTest/Validators/Partner/CreatePartnersValidatorTests.cs
dev
* [Github ticket](https://github.com/ita-social-projects/StreetCode/issues/2050)
Absence of validation rule for partner's title to be unique
Added new validation rule.
> Added validation rule for partner's title to be unique.

- Streetcode/Streetcode.DAL/Persistence/Migrations/20250203093100_NewsUpdate.Designer.cs
- Streetcode/Streetcode.DAL/Persistence/Migrations/20250203093100_NewsUpdate.cs
- Streetcode/Streetcode.DAL/Persistence/ScriptsMigration/Script_20250118172930_ChangeConstraints.sql
- Streetcode/Streetcode.DAL/Persistence/ScriptsMigration/UpdateNews.sql
News constraint
removed news constraint
> removed constraint from news
